#!/bin/bash

echo "🚨 AI GENERATION TROUBLESHOOTING - ProjectAdd Form"
echo "=================================================="

echo ""
echo "🎯 ISSUE:"
echo "========"
echo "AI content is no longer populating the Add form after button conflict fix"

echo ""
echo "🔍 DEBUGGING STEPS:"
echo "=================="

echo ""
echo "1. START APPLICATION:"
echo "   dotnet run"

echo ""
echo "2. OPEN BROWSER DEVELOPER TOOLS:"
echo "   - Press F12"
echo "   - Go to Console tab"
echo "   - Clear any existing messages"

echo ""
echo "3. NAVIGATE TO ADD PROJECT:"
echo "   - Go to: /ProjectAdd"
echo "   - Fill in MINIMAL data:"
echo "     Repository URL: https://github.com/markhazleton/js-dev-env"
echo "     (Leave title and summary empty to test validation)"

echo ""
echo "4. TEST AI GENERATION WITH DEBUGGING:"
echo "   - Click 'Generate AI Content'"
echo "   - Watch BOTH browser console AND application logs"

echo ""
echo "🔍 EXPECTED BROWSER CONSOLE OUTPUT:"
echo "==================================="

echo ""
echo "✅ SUCCESSFUL AI GENERATION:"
echo "AI Generate button clicked - submitting to OnPostGenerateAiContentAsync()"
echo "AI Generation validation - Title: [empty] Summary: [empty] RepoUrl: https://github.com/markhazleton/js-dev-env"
echo "AI Generation validation passed - proceeding with form submission"

echo ""
echo "❌ VALIDATION BLOCKING AI:"
echo "AI Generate button clicked - submitting to OnPostGenerateAiContentAsync()"
echo "AI Generation validation - Title: [empty] Summary: [empty] RepoUrl: [empty]"
echo "AI Generation prevented - insufficient data"
echo "Alert: 'Please provide at least a project title, summary, or GitHub repository URL...'"

echo ""
echo "🔍 EXPECTED APPLICATION LOG OUTPUT:"
echo "==================================="

echo ""
echo "✅ SUCCESSFUL AI GENERATION:"
echo "[ProjectAdd] ===== STARTING AI GENERATION PROCESS ====="
echo "[ProjectAdd] OnPostGenerateAiContentAsync() method called - THIS IS AI GENERATION, NOT SAVE"
echo "[ProjectAdd] Calling ProjectService.AutoGenerateProjectDataAsync..."
echo "[ProjectService] AutoGenerateProjectDataAsync called for project: [title]"
echo "[ProjectAdd] AI generation completed successfully"

echo ""
echo "❌ AI GENERATION NOT TRIGGERED:"
echo "(No AI generation logs appear - validation prevented form submission)"

echo ""
echo "🔧 POTENTIAL ISSUES AND FIXES:"
echo "=============================="

echo ""
echo "🎯 ISSUE 1: JavaScript Validation Too Strict"
echo "SYMPTOMS: Alert popup prevents AI generation"
echo "SOLUTION: Provide at least one field (repository URL is best)"

echo ""
echo "🎯 ISSUE 2: Form Not Submitting to Correct Handler"
echo "SYMPTOMS: Form submits but logs show OnPost() instead of OnPostGenerateAiContentAsync()"
echo "SOLUTION: Check if asp-page-handler attribute is working"

echo ""
echo "🎯 ISSUE 3: JavaScript Error Preventing Submission"
echo "SYMPTOMS: No console logs appear, button doesn't respond"
echo "SOLUTION: Check browser console for JavaScript errors"

echo ""
echo "🎯 ISSUE 4: Model Binding Issues"
echo "SYMPTOMS: Form submits but fields are empty in backend"
echo "SOLUTION: Check model binding and property names"

echo ""
echo "🧪 QUICK TESTS:"
echo "=============="

echo ""
echo "TEST 1 - Minimum Data:"
echo "✅ Repository URL: https://github.com/markhazleton/js-dev-env"
echo "✅ Title: [empty]"
echo "✅ Summary: [empty]"
echo "SHOULD: Pass validation and trigger AI generation"

echo ""
echo "TEST 2 - No Data:"
echo "❌ Repository URL: [empty]"
echo "❌ Title: [empty]"
echo "❌ Summary: [empty]"
echo "SHOULD: Show validation alert and prevent submission"

echo ""
echo "TEST 3 - Title Only:"
echo "❌ Repository URL: [empty]"
echo "✅ Title: Test Project"
echo "❌ Summary: [empty]"
echo "SHOULD: Pass validation and trigger AI generation"

echo ""
echo "🔍 NETWORK TAB DEBUGGING:"
echo "========================="

echo ""
echo "1. Open Network tab in browser dev tools"
echo "2. Click 'Generate AI Content'"
echo "3. Look for POST request:"

echo ""
echo "✅ CORRECT REQUEST:"
echo "POST /ProjectAdd?handler=GenerateAiContent"
echo "Status: 200 OK"
echo "Response: HTML page with populated fields"

echo ""
echo "❌ INCORRECT REQUEST:"
echo "POST /ProjectAdd (no handler parameter)"
echo "OR: No POST request at all (validation prevented)"

echo ""
echo "🚀 QUICK FIX ATTEMPTS:"
echo "====================="

echo ""
echo "1. TRY WITH REPOSITORY URL ONLY:"
echo "   - Fill only Repository URL field"
echo "   - Click Generate AI Content"
echo "   - Should work if validation is the issue"

echo ""
echo "2. CHECK BUTTON FUNCTIONALITY:"
echo "   - Right-click 'Generate AI Content' button"
echo "   - Inspect element"
echo "   - Verify asp-page-handler=\"GenerateAiContent\" is present"

echo ""
echo "3. BYPASS VALIDATION TEMPORARILY:"
echo "   - Open browser console"
echo "   - Type: document.querySelector('button[asp-page-handler=\"GenerateAiContent\"]').click()"
echo "   - This bypasses JavaScript validation"

echo ""
echo "🎯 REPORT BACK WITH:"
echo "==================="
echo "1. Browser console output when clicking AI button"
echo "2. Application log output (if any)"
echo "3. Network tab requests"
echo "4. Whether form submits or gets blocked by validation"

echo ""
echo "📝 LIKELY CAUSE:"
echo "==============="
echo "The JavaScript validation is probably too strict and blocking"
echo "the AI generation when fields are empty. Try filling at least"
echo "the Repository URL field before clicking Generate AI Content."
