#!/bin/bash

echo "🚨 DEBUGGING APPLICATION CRASH ON SAVE"
echo "======================================="

echo ""
echo "🔍 ISSUE IDENTIFIED:"
echo "==================="
echo "AI Generation: ✅ Working perfectly"
echo "Save Button Click: ❌ Application crashes/exits with code -1"
echo "JavaScript Errors: jquery.validate.min.js 404 errors"

echo ""
echo "🎯 ROOT CAUSE ANALYSIS:"
echo "======================="
echo "The app is crashing when the save button is clicked, likely due to:"
echo "1. Missing jQuery validation libraries causing JS errors"
echo "2. Possible exception in the OnPost() method"
echo "3. Model validation or binding issues"

echo ""
echo "✅ FIXES APPLIED:"
echo "=================="

echo ""
echo "1. 🔧 Removed jQuery Validation Dependencies:"
echo "   - Removed @await Html.PartialAsync(\"_ValidationScriptsPartial\")"
echo "   - This eliminates the 404 errors for missing validation files"

echo ""
echo "2. 📊 Enhanced JavaScript Debugging:"
echo "   - Added comprehensive console logging for save button"
echo "   - Form data inspection before submission"
echo "   - Error catching in button handler"

echo ""
echo "3. 🛡️ Enhanced Backend Error Handling:"
echo "   - Comprehensive exception catching in OnPost()"
echo "   - Detailed logging of any exceptions"
echo "   - Stack trace logging for debugging"

echo ""
echo "🧪 TESTING STEPS:"
echo "================"

echo ""
echo "1. START APPLICATION:"
echo "   dotnet run"

echo ""
echo "2. OPEN BROWSER DEV TOOLS:"
echo "   - Press F12"
echo "   - Go to Console tab"
echo "   - Clear any existing messages"

echo ""
echo "3. TEST THE PROCESS:"
echo "   - Navigate to /ProjectEdit (for new project)"
echo "   - Add Repository URL: https://github.com/markhazleton/js-dev-env"
echo "   - Click 'Generate AI Content' (should work fine)"
echo "   - Click 'Save Project' (the problematic action)"

echo ""
echo "🔍 DEBUGGING OUTPUT TO WATCH:"
echo "============================="

echo ""
echo "📱 BROWSER CONSOLE (Expected):"
echo "Save Project button clicked - starting save process"
echo "Save mode detected: NEW PROJECT"
echo "Save Project button clicked - submitting to OnPost()"
echo "Form action: /ProjectEdit"
echo "Form method: post"
echo "Form data being submitted:"
echo "  Project.Title: Bootstrap 5 + Express.js Web App Starter Kit"
echo "  Project.Description: [description content]"
echo "  Project.Link: [link]"
echo "  Project.Slug: [slug]"

echo ""
echo "📊 SERVER LOGS (Expected Success):"
echo "[ProjectEdit] ===== STARTING PROJECT ADD PROCESS ====="
echo "[ProjectEdit] OnPost() method called - THIS IS THE REGULAR SAVE, NOT AI GENERATION"
echo "[ProjectEdit] Project ID: 0 (IsNew: True)"
echo "[ProjectEdit] Model validation state: True"
echo "[ProjectEdit] Model validation passed"
echo "[ProjectEdit] Calling ProjectService.AddProject..."
echo "[ProjectService] ===== STARTING ADD PROJECT PROCESS ====="
echo "[ProjectService] Project added successfully"
echo "[ProjectEdit] Operation completed successfully, redirecting to Projects page"

echo ""
echo "❌ SERVER LOGS (If Error Occurs):"
echo "[ProjectEdit] CRITICAL ERROR occurred while add project"
echo "[ProjectEdit] Exception: [ExceptionType]"
echo "[ProjectEdit] Message: [Error message]"
echo "[ProjectEdit] StackTrace: [Full stack trace]"

echo ""
echo "🎯 LIKELY SCENARIOS:"
echo "==================="

echo ""
echo "SCENARIO 1: Validation Issues"
echo "- Browser console shows form data"
echo "- Server logs show validation errors"
echo "- No crash, just validation failure"

echo ""
echo "SCENARIO 2: Model Binding Issues"
echo "- Browser console shows form submission"
echo "- Server logs show OnPost() called but model is empty/invalid"
echo "- Possible property binding problems"

echo ""
echo "SCENARIO 3: ProjectService.AddProject() Exception"
echo "- Browser console shows form submission"
echo "- Server logs show OnPost() called, validation passed"
echo "- Exception occurs in ProjectService.AddProject()"
echo "- This is where the crash likely happens"

echo ""
echo "SCENARIO 4: File System/Permissions Issue"
echo "- Browser console shows form submission"
echo "- Server logs show attempt to save to JSON file"
echo "- Exception occurs during file write operation"

echo ""
echo "🔧 DEBUGGING COMMANDS:"
echo "====================="

echo ""
echo "# Check if projects.json file exists and is writable"
echo "ls -la /path/to/projects.json"

echo ""
echo "# Check application permissions"
echo "# Ensure the app can write to the JSON file location"

echo ""
echo "# Monitor in real-time"
echo "# Keep both browser console and server console open"
echo "# Watch the sequence of events when clicking Save"

echo ""
echo "🚀 QUICK TEST:"
echo "=============="

echo ""
echo "After applying these fixes:"
echo "1. Run the application"
echo "2. Add a new project with AI generation"
echo "3. Click 'Save Project'"
echo "4. Watch both browser console and server logs"
echo "5. Report back which scenario matches what you see"

echo ""
echo "The enhanced logging should now clearly show us exactly where the failure occurs!"
