#!/bin/bash

echo "🔍 COMPREHENSIVE PROJECT SAVE TROUBLESHOOTING"
echo "=============================================="

echo ""
echo "🚨 ISSUE: Projects showing AI data in form but not saving to projects.json"
echo "========================================================================="

echo ""
echo "📋 STEP-BY-STEP DEBUGGING PROCESS:"
echo "=================================="

echo ""
echo "🔍 PHASE 1: Pre-Test Verification"
echo "--------------------------------"
echo "1. Start your application: dotnet run"
echo "2. Check initial project count:"
echo "   GET https://localhost:7219/api/test/debug-project-counts"
echo "3. Check current project list:"
echo "   GET https://localhost:7219/api/test/debug-project-list"

echo ""
echo "📝 PHASE 2: Test AI Generation + Save"
echo "------------------------------------"
echo "1. Navigate to: Add Project page"
echo "2. Fill in:"
echo "   - Repository URL: https://github.com/markhazleton/js-dev-env"
echo "   - Title: JavaScript Development Environment Test"
echo "   - Summary: Testing AI generation and save functionality"
echo "3. Click 'Generate AI Content'"
echo "4. Verify all sections populate"
echo "5. Click 'Save Project'"

echo ""
echo "🔍 PHASE 3: Check Logs During Save"
echo "---------------------------------"
echo "Watch the application console for these log entries:"

echo ""
echo "✅ EXPECTED SUCCESS LOG SEQUENCE:"
echo "[ProjectAdd] ===== STARTING PROJECT SAVE PROCESS ====="
echo "[ProjectAdd] Model validation state: True"
echo "[ProjectAdd] Model validation passed"
echo "[ProjectAdd] Calling ProjectService.AddProject..."
echo "[ProjectService] ===== STARTING ADD PROJECT PROCESS ====="
echo "[ProjectService] Adding project: JavaScript Development Environment Test"
echo "[ProjectService] Current project count: 13"
echo "[ProjectService] Before PrepareForPersistence - SEO: True, OG: True, Twitter: True..."
echo "[ProjectService] Calling PrepareForPersistence..."
echo "[ProjectService] PrepareForPersistence completed successfully"
echo "[ProjectService] After PrepareForPersistence - SEO: True, OG: True, Twitter: True..."
echo "[ProjectService] Required field validation passed"
echo "[ProjectService] Assigned new ID: 14"
echo "[ProjectService] No duplicate ID found, proceeding with clone and add"
echo "[ProjectService] Project cloned successfully"
echo "[ProjectService] Project added to in-memory list. New count: 14"
echo "[ProjectService] Calling SaveProjects..."
echo "[ProjectService] ===== STARTING SAVE PROJECTS TO FILE ====="
echo "[ProjectService] Project count to save: 14"
echo "[ProjectService] Starting JSON serialization..."
echo "[ProjectService] JSON serialization successful"
echo "[ProjectService] Writing JSON to file..."
echo "[ProjectService] File write successful"
echo "[ProjectService] Read-back verification successful. Projects in file: 14"
echo "[ProjectService] ===== SAVE PROJECTS COMPLETED SUCCESSFULLY ====="
echo "[ProjectService] Project added successfully with ID: 14, Total projects: 14"
echo "[ProjectAdd] ProjectService.AddProject completed successfully"

echo ""
echo "❌ POTENTIAL FAILURE POINTS TO WATCH FOR:"
echo "----------------------------------------"
echo "1. Model Validation Failure:"
echo "   [ProjectAdd] Model validation failed"
echo "   Look for: Validation error messages"
echo ""
echo "2. Required Field Issues:"
echo "   [ProjectService] Validation failed for required fields: [field names]"
echo ""
echo "3. File Permission Issues:"
echo "   [ProjectService] File write permission check failed"
echo "   [ProjectService] File write failed"
echo ""
echo "4. JSON Serialization Issues:"
echo "   [ProjectService] JSON serialization failed"
echo ""
echo "5. PrepareForPersistence Stripping Data:"
echo "   [ProjectService] After PrepareForPersistence - SEO: False, OG: False..."

echo ""
echo "🔍 PHASE 4: Post-Save Verification"
echo "---------------------------------"
echo "After clicking Save, immediately check:"
echo "1. Project count: GET https://localhost:7219/api/test/debug-project-counts"
echo "2. Project list: GET https://localhost:7219/api/test/debug-project-list"
echo "3. Browser should redirect to Projects page"
echo "4. Projects page should show 14 projects instead of 13"

echo ""
echo "🧪 QUICK API TESTS (when server is running):"
echo "============================================="

echo ""
echo "# Check current counts"
echo "curl -k https://localhost:7219/api/test/debug-project-counts"

echo ""
echo "# Check project list"
echo "curl -k https://localhost:7219/api/test/debug-project-list"

echo ""
echo "🔧 SPECIFIC ISSUES TO INVESTIGATE:"
echo "=================================="

echo ""
echo "🎯 Issue 1: Model Binding Problems"
echo "If form data isn't binding properly:"
echo "- Check browser developer tools > Network tab"
echo "- Verify POST data is being sent correctly"
echo "- Look for any JavaScript errors preventing form submission"

echo ""
echo "🎯 Issue 2: Validation Failures"
echo "If required field validation fails:"
echo "- Title must not be empty"
echo "- Description must not be empty" 
echo "- Link must be valid URL (auto-populated from repository URL)"
echo "- Slug must be valid (auto-generated from title)"

echo ""
echo "🎯 Issue 3: File System Issues"
echo "Check if the application can write to the projects.json file:"
echo "- File path permissions"
echo "- Directory existence"
echo "- Disk space"

echo ""
echo "🎯 Issue 4: PrepareForPersistence Stripping Data"
echo "If AI data is being removed during preparation:"
echo "- Check the 'After PrepareForPersistence' log entries"
echo "- If SEO/OG/Twitter show False, the IsCompletelyEmpty checks might be too aggressive"

echo ""
echo "🎯 Issue 5: Exception Handling"
echo "Look for any unhandled exceptions that might be silently failing"

echo ""
echo "📊 WHAT TO REPORT:"
echo "=================="
echo "After testing, provide:"
echo "1. Complete log output from application console"
echo "2. Results from debug API endpoints"
echo "3. Browser developer tools console errors (if any)"
echo "4. Network tab showing the POST request to save the project"
echo "5. Whether redirect to Projects page happens"
echo "6. Current projects.json file content"

echo ""
echo "🎯 EXPECTED RESOLUTION:"
echo "======================"
echo "With the enhanced logging, we should be able to pinpoint exactly where the save process is failing:"
echo "- Model validation issues"
echo "- Data preparation problems"
echo "- File system write failures"
echo "- JSON serialization errors"
echo "- ID assignment conflicts"

echo ""
echo "🚀 Start your application and run through the test process!"
echo "The detailed logs will reveal exactly what's happening during the save."
