name: Azure Static Web Apps CI/CD

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened, closed]
        branches:
            - main

jobs:
    build_and_deploy_job:
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        runs-on: ubuntu-latest
        name: Build and Deploy Job
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true
                  lfs: false

            # Setup Node.js environment
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20" # Specify the Node.js version you want to use
                  cache: "npm" # Enable npm caching for faster builds

            # Install dependencies and run build script
            - name: Install and Build
              run: |
                  npm ci
                  npm run build
              env:
                  NODE_ENV: production

            # Deploy to Azure Static Web Apps
            - name: Build And Deploy
              id: builddeploy
              uses: Azure/static-web-apps-deploy@v1
              env:
                  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_STONE_0F5CD1910 }}
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_STONE_0F5CD1910 }}
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  action: "upload"
                  app_location: "/docs" # This may need to be adjusted based on your build output directory
                  api_location: ""
                  output_location: "" # This should be the directory where your build script outputs the files

            # Trigger IndexNow after successful deployment
            - name: Trigger IndexNow
              if: success()
              run: |
                  curl -X POST "https://www.bing.com/indexnow" \
                  -H "Content-Type: application/json" \
                  -d '{
                        "host": "markhazleton.com",
                        "key": "63a3bf5bd1c146adb1921e4532d443f5",
                        "urlList": [],
                        "keyLocation": "https://markhazleton.com/63a3bf5bd1c146adb1921e4532d443f5.txt",
                        "sitemapLocations": ["https://markhazleton.com/sitemap.xml"]
                      }'

            # Notify on failure
            - name: Notify on Failure
              if: failure()
              uses: actions/github-script@v7
              with:
                  script: |
                      github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: '❌ Azure Static Web Apps deployment failed. Please check the workflow logs.'
                      })

    close_pull_request_job:
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        name: Close Pull Request Job
        steps:
            - name: Close Pull Request
              id: closepullrequest
              uses: Azure/static-web-apps-deploy@v1
              env:
                  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_STONE_0F5CD1910 }}
              with:
                  app_location: "/docs"
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_STONE_0F5CD1910 }}
                  action: "close"
