name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Setup Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Specify the Node.js version you want to use

      # Install dependencies and run build script
      - name: Install and Build
        run: |
          npm install
          npm run build

      # Deploy to Azure Static Web Apps
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_STONE_0F5CD1910 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/docs" # This may need to be adjusted based on your build output directory
          api_location: ""
          output_location: "" # This should be the directory where your build script outputs the files

      # Trigger IndexNow after successful deployment
      - name: Trigger IndexNow
        if: success()
        run: |
          curl -X POST "https://www.bing.com/indexnow" \
          -H "Content-Type: application/json" \
          -d '{
                "host": "markhazleton.com",
                "key": "63a3bf5bd1c146adb1921e4532d443f5",
                "keyLocation": "https://markhazleton.com/indexnow.txt",
                "sitemapLocations": ["https://markhazleton.com/sitemap.xml"]
              }'

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
            app_location: "/docs"
            azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_STONE_0F5CD1910 }}
            action: "close"
